# -*- coding: utf-8 -*-
"""Lab 1 - Funciones.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bLZKRGVsaAsafi5wvvHrib37Z43UV-Qy
"""

#Ejercicio de las figuras geométricas en funciones como trabajo en equipo
#Estudiantes:
#Luis Antonio Montes de Oca
#Alexis Solis
#Aslie Cárdenas
#Jose Jimenez

import math

#Circulo
def calcular_area_circulo(radio):
  return math.pi * radio**2

def calcular_perimetro_circulo(radio):
  return 2*math.pi * radio

radio=float(input("Digite el valor del radio: "))
area=calcular_area_circulo(radio)
perimetro=calcular_perimetro_circulo(radio)
print("El area es: ",area)
print("El perimetro: ", perimetro)

#Cuadrado
def calcular_area_cuadrado(lado):
  return lado * lado

def calcular_perimetro_cuadrado(lado):
  return 4 * lado

lado= int(input("Digite un valor:"))
area=calcular_area_cuadrado(lado)
perimetro=calcular_perimetro_cuadrado(lado)
print("El area es: ",area)
print("El perimetro: ", perimetro)

#Rectangulo
print("Calcular area rectangulo")
def calcular_area_rectangulo(base, altura):
  return base * altura

def calcular_perimetro_rectangulo(base, altura):
  return (2 * base) + (2 * altura)

base= int(input("Digite el valor de base: "))
altura= int(input("Digite el valor de la altura: "))
area= calcular_area_rectangulo(base, altura)
perimetro=calcular_perimetro_rectangulo(base, altura)
print("El area es: ",area)
print("El perimetro: ", perimetro)

#Paralelo
def area_paralelo(base, altura):
  return base*altura

def perimetro_paralelo(l1, l2):
  return (l1*2)+(l2*2)

base=int(input("Digite la medida de la base: "))
altura=int(input("Digite la medida de la altura: "))
lado=int(input("Digite la medida del lado: "))

area=area_paralelo(base, altura)
perimetro=perimetro_paralelo(base, lado)

print("El area es de: ", area)
print("El perimetro es de: ", perimetro)

#Triangulo equilatero
lado = float(input("Digite el tamano del lado: "))

def triangulo_equilatero_area (lado ):
    return lado**2*math.sqrt(3)/4

def triangulo_equilatero_perimetro(lado ):
    return 3*lado

area = triangulo_equilatero_area(lado)
perimetro = triangulo_equilatero_perimetro(lado)
print("El area es: " +str(area))
print("El area es: " +str(perimetro))

#Triangulo
print("Triangulo")
def calcular_area_triangulo(base, altura):
  return (base * altura)/2

def calcular_perimetro_triangulo(lado1, lado2, lado3):
  return lado1 + lado2 + lado3

base= int(input("Digite el valor de la base: "))
altura= int(input("Digite el valor de la altura: "))
area=calcular_area_triangulo(base, altura)
lado1= int(input("Digite el valor del lado 1: "))
lado2= int(input("Digite el valor del lado 2: "))
lado3= int(input("Digite el valor del lado 3: "))
perimetro=calcular_perimetro_triangulo(lado1, lado2, lado3)
print("El area es: ",area)
print("El perimetro: ", perimetro)

#Rombo
print("Rombo")
def calcular_area_rombo(dMayor, dMenor):
  return (dMayor * dMenor)/2

def calcular_perimetro_rombo(lado):
  return lado * 4

dMayor= int(input("Digite el valor de la diagonal mayor: "))
dMenor= int(input("Digite el valor de la diagonal menor: "))
area=calcular_area_rombo(dMayor, dMenor)
lado= int(input("Digite el valor de un lado : "))
perimetro=calcular_perimetro_rombo(lado)
print("El area es: ",area)
print("El perimetro: ", perimetro)

#Trapecio
print("Trapecio")
def calcular_area_trapecio(baseMenor, baseMayor, altura):
  return ((baseMenor + baseMayor)/2)*altura

def calcular_perimetro_trapecio(baseMenor, baseMayor, altura):
  return (2*(baseMayor-baseMenor))+baseMayor+baseMenor

baseMenor=float(input("Digite el valor de la base menor: "))
baseMayor=float(input("Digite el valor de la base mayor: "))

altura=float(input("Digite el valor de la altura: "))
area=calcular_area_trapecio(baseMenor, baseMayor, altura)
perimetro=calcular_perimetro_trapecio(baseMenor, baseMayor, altura)
print("El area es: ",area)
print("El perimetro: ", perimetro)

#Poligono regular
print("Poligono regular")
def calcular_area_poligono_regular(apotema, perimetro):
  return (apotema*perimetro)/2

def calcular_perimetro_poligono_regular(numeroLado, lado):
  return numeroLado*lado

apotema=float(input("Digite el valor de la apotema : "))
numeroLados=float(input("Digite la cantidad de lados: "))
lado = float(input("Digite el valor del lado: "))
perimetro=calcular_perimetro_poligono_regular(numeroLados, lado)
area=calcular_area_poligono_regular(apotema, perimetro)

print("El area es: ",area)
print("El perimetro: ", perimetro)